name = "absensi-sd-ypu"
compatibility_date = "2026-05-28"
pages_build_output_dir = "."

[[d1_databases]]
binding = "DB"
database_name = "absensimapel"
database_id = "c9fc7057-2764-4366-ace0-6dea8882106e"
